export const API_BASE_URL = "https://admin.oncquestlabs.com/api" /*"http://18.219.144.119/oncquest/api"  "https://admin.oncquestlabs.com/api" */;
export const SITE_URL = "https://oncquestlabs.com";
export const Url = {
    login: "/auth/login",
    register: "/auth/register",
    apiGetToken: "/api-get-token",
    dashboard: "/dashboard",
    testimonials: "/testimonials/list",
    state:"/states",
    city:"/cities",
    departmentList: "/departments",
    departmentDetails: "/department/details",
    departmentBySlug: "/department",
    doctorList:"/doctors",
    doctorDetails:"/doctor",
    doctorBySlug:"/doctor",
    centerList:"/centres",
    centerDetails:"/centre/details",
    centerBySlug:"/centre",
    nearByCenter: "/centre/nearby",
    tests: "/tests",
    testBySlug: "/test",
    testById: "/test/details",
    packages: "/packages",
    packageById: "/package/details",
    packageBySlug: "/package",
    packageComponent: "/package/components",
    facilities: "/facilities",
    pgoptions: "/pgoptions",
    subcategories: "/subcategories",
    querySubmit: "/query/submit",
    enquirySubmit: "/enquiry/submit",
    enquiryPartner: "/enquiry/partner",
    uploadAttachment: "/upload-attachment",
    uploadPrecription: "/booking/uploadPrescriptions",
    bookingEnquiry: "/booking/enquiry",
    generalDetails: "/general/details",
    cme: "/cme",
    newsAndUpdate: "/news-events",
    pressRealease: "/pressrelease/list",
    pressreleaseBySlug: "/pressrelease",
    allOffer: "/coupons",
    offerById: "/coupon/details",
    faq: "/faqs",
    seoDetail: "/seo-details",
    sendOtp: "/send-otp",
    verifyOtp: "/verify-otp",
    slot: "/available/slots",
    createBooking: "/create-booking",
    jobList:"/jobs",
    jobApply: "/apply-job",
    brochures: "/brochure/list",
    newsletter: "/newsletter/subscribe",
    collectionForm: "/create-collection",
    membershipForm: "/membership/submit"
}