
export const ROUTE = {
    HOME: "/",
    SIGNUP: "/signup",
    MYPROFILE:"/my-profile",
    LOGIN: "/login",
    THANKYOU: "/thank-you",
    PAYMENT_THANKYOU:"/payment-thank-you",
    UPLOADPRESCRIPTION: "/upload-prescription",
    BROCHURES: "/brochures",
    TEAM: "/team",
    DOCTORDETAILS: "/doctor",
    DEPARTMENTDETAILS: "/department",
    DEPARTMENT: "/departments",
    BOOKATEST: "/book-a-test",
    BOOKAPACKAGE: "/health-packages",
    TESTDETAILS: "/test",
    PACKAGEDETAILS: "/package",
    CENTERDETAILS: "/centre",
    CENTER: "/centres",
    DOWNLOADREPORT: "/download-report",
    GENERALENQUIRY: "/general-enquiry",
    OFFER: "/offers",
    TESTIMONIAL: "/testimonials",
    NEWSANDUPDATES: "/news-updates",
    NEWSANDUPDATESDETAIL: "/news-update",
    PRESSREALEASEDETAIL: "/press-realease",
    FAQ: "/faq",
    CHECKOUT: "/checkout",
    CORPORATEOFFICE: "/corporate-office",
    SERACHFORTEST: "/search-for-test",
    CUSTOMLANDING: "/custom-landing",
    NATIONREFLAB: "/national-reference-lab",
    ECME: "/ecme",
    CAREER: "/career",
    ENDEVOUR: "/endeavour",
    OVERVIEW: "/overview",
    DIRECTORMESSAGE: "/directors-message",
    ACCREDATITION: "/accreditation",
    QUALITYMANAGEMENT: "/quality-management",
    AWARD: "/award-recognition",
    PRIVACY: "/privacy-policy",
    TERMSCONDITION: "/terms-condition",
    DISCLAIMER: "/disclaimer",
    HEALTHENQUIRY: "/corporate",
    HOMECOLLECTION: "/home-collection",
    BECOMWEPARTNER: "/partner-with-us",
    BECOMEVENDOR: "/vendor-with-us",
    NEUROLOGY: "/neurology",
    ALLERGY: "/allergy",
    MAMAPRINT: "/mamma-print",
    QUICKLINKS: "/quick-links",
    PREVENTIVEHEALTHPKJ: "/preventive-health-check-packages",
    GURUGRAMLAB: "/gurugram-lab",
    BENGALURULAB: "/bengaluru-lab",
    KOLKATALAB: "/kolkata-lab",
    CANCER: '/cancer',
    PRENATALTESTING: '/prenatal-testing',
    LUDHIANALAB: '/ludhiana-lab',
    VIDEOSECTION: '/youtube-video-section',
    CLINICALTRIAL: '/clinical-trial',
    PRIVILEGEMEMBERSHIP: '/privilege-membership-card',
    PRIVILEGEMEMBERSHIPDOCTOR: '/privilege-membership-card-doctor',
    PATHLOGYTEST: '/pathology-test',
    // PATHLOGYTESTLOCAL: '/book-a-test',
    ERRORPAGE: '/404error'


}